spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haowei_laundry_prod
    username: haowei_laundry_prod_user
    password: haowei
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false